-- options.lua (QuestKing) — 12.0-ready
-- Refactored defaults and structure; override safely via options_override.lua

local addonName, QuestKing = ...

local opt = {}
QuestKing.options = opt

----------------------------------------------------------------------
-- How to customize
--   • Do NOT edit this file if you can avoid it.
--   • Put your changes in options_override.lua (or rename to
--     options_override_custom.lua to protect it from updates).
----------------------------------------------------------------------


----------------------------------------------------------------------
-- Typography & layout
----------------------------------------------------------------------

-- Font files (use STANDARD_TEXT_FONT when available so UI packs/theme swaps apply)
opt.font                = _G.STANDARD_TEXT_FONT or "Fonts\\FRIZQT__.TTF"
opt.fontChallengeTimer  = opt.font
opt.fontSize            = 12            -- base size for tracker text
opt.fontStyle           = "NONE"        -- e.g. "NONE", "OUTLINE", "THICKOUTLINE", "MONOCHROME"
opt.fontLayer           = "OVERLAY"     -- Draw layer for font strings

-- Core sizing
opt.buttonWidth         = 230           -- width of each watch button (title + lines)
opt.lineHeight          = 16            -- height per objective line
opt.titleHeight         = 14            -- height of the title line

-- Global scale/alpha (with DB override support)
opt.trackerScale        = 1.0
opt.dbAllowTrackerScale = true          -- allow persisting scale in SVs

opt.trackerAlpha        = 0.95
opt.dbAllowTrackerAlpha = true          -- allow persisting alpha in SVs


----------------------------------------------------------------------
-- Behavior toggles
----------------------------------------------------------------------

-- If true, QuestKing will attempt to suppress Blizzard's Objective Tracker.
-- Warning: aggressive suppression of Blizzard tracker/map UI can taint protected
-- code paths on modern Retail clients. Keep this false unless you are doing
-- targeted testing and know the risk.
opt.disableBlizzard = false

-- If true, QuestKing will enable PetTracker integration helpers.
-- This is disabled by default because reparenting third-party objective frames
-- into a custom tracker is a common taint source on modern clients.
opt.enablePetTrackerCompatibility = false

-- Show special popup when looting an item that starts a quest
opt.enableItemPopups = true

-- Controls how completed objectives are shown:
--   false   = hide completed objectives as you progress
--   true    = show completed objectives while the quest is incomplete
--   "always"= even if the quest is complete, still show objectives
opt.showCompletedObjectives = true

-- Hide objectives that are superseded by newer steps (e.g., scenario score tiers, invasion scores)
opt.hideSupersedingObjectives = true

-- Item/Reward anchoring relative to the tracker buttons
--   "right" (default) places the usable item just to the right of the line stack
--   "left"  places it to the left
opt.itemAnchorSide   = "right"
opt.rewardAnchorSide = "right"

-- Tooltip handling for tracker entries
--   anchor: e.g. "ANCHOR_RIGHT", "ANCHOR_LEFT", "ANCHOR_CURSOR", etc.
--   scale:  nil to use default; number to force tooltip scale (e.g., 0.9, 1.1)
opt.tooltipAnchor = "ANCHOR_RIGHT"
opt.tooltipScale  = nil


----------------------------------------------------------------------
-- Scenario / raid tracker behavior
----------------------------------------------------------------------

-- Master switch for scenario-style tracker content.
-- If false, QuestKing will not render scenario / delve / dungeon / raid
-- objective blocks through the scenario tracker path.
opt.enableScenarioTracker = true

-- Respect Blizzard's scenario-criteria visibility state when available.
-- If true, QuestKing hides criteria rows when Blizzard reports they should
-- not be shown and falls back to stage text where appropriate.
-- If false, QuestKing will still try to render criteria whenever it has them.
opt.respectScenarioCriteriaVisibility = true

-- If true, instanceType == "raid" with valid scenario-backed data will be
-- labeled as Raid in the tracker header.
-- If false, QuestKing falls back to the normal scenario/dungeon labeling rules.
opt.preferRaidScenarioLabel = true

-- If true, QuestKing may show scenario-backed objective blocks in raids.
-- This does not invent raid objectives on its own; Blizzard still has to
-- expose them through the scenario APIs.
opt.showScenarioObjectivesInRaids = true

-- If true, QuestKing may still show scenario-backed blocks for party/dungeon
-- content even when Blizzard is not using the simplest IsInScenario gate.
opt.allowInstanceScenarioFallback = true

-- If true, spell names from scenario steps may be listed in the tooltip.
opt.showScenarioSpellsInTooltip = true


----------------------------------------------------------------------
-- Tracker placement & drag
----------------------------------------------------------------------

-- If true, the tracker can be dragged (saves exact position per character)
-- If false, the tracker uses preset points & you can cycle them with Shift+Click on the minimize button
opt.allowDrag              = true
opt.hideToggleButtonBorder = false

-- Preset position list used when allowDrag=false or when cycling with Shift+Click
-- Format: { point, relativeTo, relativePoint, x, y }
opt.positionPresets = {
    { "TOPRIGHT",   "UIParent", "TOPRIGHT",    -8, -160 },
    { "TOPRIGHT",   "UIParent", "TOPRIGHT",  -180,  -20 },
    { "TOPLEFT",    "UIParent", "TOPLEFT",      8, -160 },
    { "BOTTOMRIGHT","UIParent", "BOTTOMRIGHT", -8,  180 },
}


----------------------------------------------------------------------
-- Background styles
-- Choose ONE of these by enabling the matching flag.
--  • Advanced background gives a framed panel with its own alpha and border.
--  • Simple backdrop uses a plain backdrop on the tracker frame.
----------------------------------------------------------------------

-- Advanced background (panel behind the whole tracker)
opt.enableAdvancedBackground = false
opt.advancedBackgroundTable = {
    bgFile   = "Interface\\Tooltips\\UI-Tooltip-Background",
    edgeFile = "Interface\\Tooltips\\UI-Tooltip-Border",
    tile     = false,
    tileSize = 0,
    edgeSize = 12,
    insets   = { left = 3, right = 3, top = 3, bottom = 3 },

    -- Convenience fields the addon expects
    _backdropColor = { 0, 0, 0, 0.55 },
    _borderColor   = { 0.2, 0.2, 0.2, 1.0 },
    _alpha         = 1.0,       -- overall panel alpha (independent of tracker alpha)
    _alphaStep     = 0.05,      -- mousewheel step when adjusting alpha on the toggle button
    _hideWhenEmpty = true,      -- auto-hide background if there are no rows

    -- Relative expansion to the tracker's rect (in pixels)
    _anchorPoints  = {
        topLeftX     = -6,
        topLeftY     =  6,
        bottomRightX =  6,
        bottomRightY = -6,
    },
}

-- Simple backdrop directly on the tracker (if you prefer)
opt.enableBackdrop = false
opt.backdropTable = {
    bgFile   = "Interface\\ChatFrame\\ChatFrameBackground",
    edgeFile = nil,
    tile     = false,
    tileSize = 0,
    edgeSize = 0,
    insets   = { left = 0, right = 0, top = 0, bottom = 0 },

    -- Convenience fields the addon expects
    _backdropColor = { 0, 0, 0, 0.40 },
    _alphaStep     = 0.05,
}


----------------------------------------------------------------------
-- Color palette
-- Every key here is referenced somewhere in the codebase.
----------------------------------------------------------------------

opt.colors = {
    -- Tracker header (numbers on the titlebar)
    TrackerTitlebarText        = { 0.85, 0.85, 1.00 },
    TrackerTitlebarTextDimmed  = { 0.55, 0.55, 0.60 },

    -- Section headers (e.g., “Quests”, “Achievements”)
    SectionHeader              = { 0.50, 0.80, 1.00 },

    -- Quest list
    QuestHeader                = { 1.00, 0.82, 0.00 },
    QuestHeaderCollapsed       = { 0.80, 0.60, 0.00 },
    QuestTimer                 = { 1.00, 0.40, 0.30 },
    QuestConnector             = { 0.55, 0.55, 0.55 },

    -- Objective states
    ObjectiveComplete          = { 0.20, 1.00, 0.20 },
    ObjectiveFailed            = { 1.00, 0.20, 0.20 },

    -- Objective gradient (used via util.lua GetObjectiveColor)
    ObjectiveGradient0         = { 1.00, 0.25, 0.25 }, -- 0%
    ObjectiveGradient50        = { 1.00, 0.95, 0.30 }, -- ~50%
    ObjectiveGradient99        = { 0.30, 0.95, 0.30 }, -- ~99%
    ObjectiveGradientComplete  = { 0.40, 1.00, 0.60 }, -- 100%

    -- Scenario UI
    ScenarioStageTitle         = { 1.00, 0.90, 0.40 },
    ScenarioTimer              = { 0.85, 0.75, 0.30 },

    -- Popup cards (New/Complete/Item)
    PopupOfferTitle            = { 1.00, 0.96, 0.41 },
    PopupOfferDescription      = { 1.00, 1.00, 1.00 },
    PopupOfferBackground       = { 0.12, 0.24, 0.38, 0.70 }, -- RGBA

    PopupCompleteTitle         = { 0.30, 1.00, 0.60 },
    PopupCompleteDescription   = { 1.00, 1.00, 1.00 },
    PopupCompleteBackground    = { 0.09, 0.36, 0.29, 0.70 },

    PopupItemTitle             = { 0.80, 0.90, 1.00 },
    PopupItemDescription       = { 0.90, 0.90, 0.90 },
    PopupItemBackground        = { 0.15, 0.15, 0.15, 0.60 },

    -- Achievements
    AchievementHeader          = { 0.65, 0.85, 1.00 },
    AchievementHeaderCollapsed = { 0.50, 0.65, 0.85 },
    AchievementTitle           = { 1.00, 1.00, 1.00 },
    AchievementTitleComplete   = { 0.30, 1.00, 0.60 },
    AchievementTitleGuild      = { 0.45, 0.90, 0.45 },

    AchievementDescription      = { 0.70, 0.70, 0.70 },
    AchievementCriteria         = { 0.70, 0.70, 0.70 },
    AchievementCriteriaComplete = { 0.00, 1.00, 0.00 },

    AchievementTimedTitle      = { 0.00, 1.00, 0.60 },
    AchievementTimedBackground = { 0.00, 0.90, 0.50, 0.50 }, -- RGBA
    AchievementTimer           = { 0.60, 1.00, 0.80 },
    AchievementTimerMeta       = { 0.50, 0.70, 1.00 },

    -- Animations/FX
    ObjectiveProgressFlash     = { 0.40, 1.00, 0.60 },
    ObjectiveChangedGlow       = { 0.30, 0.50, 1.00 },
    ObjectiveAlertGlow         = { 0.80, 0.60, 0.20 },
}

----------------------------------------------------------------------
-- End of defaults. Use options_override.lua to tweak anything above.
----------------------------------------------------------------------